### ISSUE TITLE
Unhandled error while trying to do Genshin Impact game repair

### ISSUE THREAD

**Issue by seriaati** [neon-nyan/Collapse#106]
# To reproduce
1. Choose "Genshin Impact" then "Global" region.
2. Click on top left hamburger menu.
3. Click "Game Repair"
4. Click "Quick Check"
5. Click "Repair Files"

# Notes
- Using 1.69.8 Stable

# Error log
```
System.Net.Http.HttpRequestException: No such host is known. (autopatchhk.yuanshen.com:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs, ValueTask, CancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String, Int32, HttpRequestMessage, Boolean, CancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String, Int32, HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, Boolean, Boolean, CancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   at Hi3Helper.Http.Session.TrySetHttpResponseAsync() in E:\myGit\CollapseLauncher\Hi3Helper.Http\Class\Session\Session.cs:line 124
   at Hi3Helper.Http.Http.InitializeMultiSession() in E:\myGit\CollapseLauncher\Hi3Helper.Http\Class\Session\SessionManager.cs:line 240
   at Hi3Helper.Http.Http.Download(String URL, String Output, Byte ConnectionSessions, Boolean Overwrite, CancellationToken ThreadToken) in E:\myGit\CollapseLauncher\Hi3Helper.Http\HttpMulti.cs:line 50
   at CollapseLauncher.Interfaces.ProgressBase`2.RunDownloadTask(Int64 assetSize, String assetPath, String assetURL, Http _httpClient, CancellationToken token) in E:\myGit\CollapseLauncher\CollapseLauncher\Classes\Interfaces\Class\ProgressBase.cs:line 289
   at CollapseLauncher.GenshinRepair.RepairAssetTypeGeneric(PkgVersionProperties asset, Http _httpClient, CancellationToken token) in E:\myGit\CollapseLauncher\CollapseLauncher\Classes\RepairManagement\Genshin\Repair.cs:line 87
   at CollapseLauncher.GenshinRepair.Repair(List`1 repairAssetIndex, CancellationToken token) in E:\myGit\CollapseLauncher\CollapseLauncher\Classes\RepairManagement\Genshin\Repair.cs:line 55
   at CollapseLauncher.GenshinRepair.Repair(List`1 repairAssetIndex, CancellationToken token) in E:\myGit\CollapseLauncher\CollapseLauncher\Classes\RepairManagement\Genshin\Repair.cs:line 55
   at CollapseLauncher.Interfaces.ProgressBase`2.TryRunExamineThrow(Task`1 action) in E:\myGit\CollapseLauncher\CollapseLauncher\Classes\Interfaces\Class\ProgressBase.cs:line 197
   at CollapseLauncher.GenshinRepair.RepairRoutine() in E:\myGit\CollapseLauncher\CollapseLauncher\Classes\RepairManagement\Genshin\GenshinRepair.cs:line 94
   at CollapseLauncher.Interfaces.ProgressBase`2.TryRunExamineThrow(Task`1 action) in E:\myGit\CollapseLauncher\CollapseLauncher\Classes\Interfaces\Class\ProgressBase.cs:line 197
   at CollapseLauncher.GenshinRepair.StartRepairRoutine(Boolean showInteractivePrompt, Action actionIfInteractiveCancel) in E:\myGit\CollapseLauncher\CollapseLauncher\Classes\RepairManagement\Genshin\GenshinRepair.cs:line 56
   at CollapseLauncher.Pages.RepairPage.StartGameRepair(Object sender, RoutedEventArgs e) in E:\myGit\CollapseLauncher\CollapseLauncher\XAMLs\MainApp\Pages\RepairPage.xaml.cs:line 96
```

**Comment by bagusnl** [comment]
Looking at the log, it seems that either your internet connection is having an issue or your DNS setting somehow blocks `autopatchhk.yuanshen.com`. Can you try again with another DNS or maybe a VPN?

**Comment by neon-nyan** [comment]
Hi @seriaati 
This should be a connection problem. The functionality seems fine on the latest release.
Will be closing this issue since no follow up on this.
