### ISSUE TITLE
Error when installing the Genshin Impact

### ISSUE THREAD

**Issue by shoucandanghehe** [neon-nyan/Collapse#148]
```
System.UriFormatException: Invalid URI: The URI is empty.
   at System.Uri.CreateThis(String, Boolean, UriKind, UriCreationOptions& )
   at System.Uri..ctor(String uriString)
   at Hi3Helper.Http.Http.GetContentLengthAsync(String Input, CancellationToken token)
   at Hi3Helper.Http.Http.TryGetContentLengthAsync(String URL, CancellationToken Token)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.TryGetPackageRemoteSize(GameInstallPackage asset, CancellationToken token)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.GetPackagesRemoteSize(List`1 packageList, CancellationToken token)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.StartPackageDownload(Boolean skipDialog)
   at CollapseLauncher.Pages.HomePage.InstallGameDialog(Object sender, RoutedEventArgs e)
```

**Comment by bagusnl** [comment]
Update:
Seems to be affecting Global region too.

**Comment by 452Foxy** [comment]
The same issue is happening to me, is there any way to fix this?

**Comment by bagusnl** [comment]
If you need to install Genshin like right now right now, unfortunately no.
After neon's deeper look at the URI, it seems that Genshin just changed how
they're shipping installation packages.

It used to be just 1 big zip file, but now they're shipping it with smaller
parted zip files. 4x 10GB + 1x 7.4GB files. This will take a little bit for
us to implement and test, so unfortunately you will have to use Genshin's
official launcher to install it.

Fear not, game update seems to be unaffected so it should work just fine.
Also, you'll able to migrate the game to be used in Collapse after
installing it using official launcher.

We're really sorry for the inconvenience.

**Comment by 452Foxy** [comment]
No problem, thanks!

**Comment by shoucandanghehe** [comment]
> Fear not, game update seems to be unaffected so it should work just fine.

After I updated the game using Collapse, there was 19G of download content in the game. Is this normal?

P.S: I don’t think this is normal, and the download speed in the game is very slow, so I tried to re-download the game, ~~and that’s how I got this issue.~~

**Comment by bagusnl** [comment]
> Is this normal?
It's not....
Can you send Collapse log on the date you applied the update?

**Comment by shoucandanghehe** [comment]
> > Is this normal?
> 
> It's not.... Can you send Collapse log on the date you applied the update?
> 
> EDIT: Also, by any chance, do you still have the old game files or have you nuked it?

sry, I uninstalled with Collapse, the game is gone
and, where is the log of Collapse saved, let me find it

**Comment by bagusnl** [comment]
> where is the log of Collapse saved, let me find it

Actually its fine now, wait for an update to come later on this

**Comment by bagusnl** [comment]
Hello, the commit is up for this issue, but still waiting for tests before getting properly pushed to release.

If you willing to test the fix, you can do that using this debug build:
https://www.mediafire.com/file/13h54rtrckdkmbe/Collapse-Debug_670b93d47783e2b409bdb2bf7bed2345fbd0c949_10.0.19041.0_Net7.0.7z/file
Please keep in mind that this debug build doesn't have any updater so make sure to use normal builds (pre/stable) after you've done with downloading the game. 

To use this build, just extract it and run CollapseLauncher.exe, all configs from normal build will be used.

Let us know if you have any difficulties or issues using this build.

**Comment by shoucandanghehe** [comment]
> Hello, the commit is up for this issue, but still waiting for tests before getting properly pushed to release.

Hi, I run a test and this is the error log 👇
It looks like the first part was deleted by mistake when unpacking
```
System.IO.FileNotFoundException: Could not find file 'E:\miHoYo\原神\Genshin Impact Game\YuanShen_3.7.0.zip.001'.
File name: 'E:\miHoYo\原神\Genshin Impact Game\YuanShen_3.7.0.zip.001'
   at System.IO.FileSystem.SetAttributes(String fullPath, FileAttributes attributes)
   at System.IO.FileInfo.set_IsReadOnly(Boolean value)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.<StartPackageInstallation>b__42_0() in E:\GitHub\Collapse\CollapseLauncher\Classes\InstallManagement\BaseClass\InstallManagerBase.cs:line 323
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.StartPackageInstallation() in E:\GitHub\Collapse\CollapseLauncher\Classes\InstallManagement\BaseClass\InstallManagerBase.cs:line 254
   at CollapseLauncher.InstallManager.Genshin.GenshinInstall.StartPackageInstallation() in E:\GitHub\Collapse\CollapseLauncher\Classes\InstallManagement\Genshin\GenshinInstall.cs:line 67
   at CollapseLauncher.Pages.HomePage.InstallGameDialog(Object sender, RoutedEventArgs e) in E:\GitHub\Collapse\CollapseLauncher\XAMLs\MainApp\Pages\HomePage.xaml.cs:line 496
```

**Comment by neon-nyan** [comment]
Hi @shoucandanghehe,
Thank you for the follow up. We will investigate this further.

**Comment by bagusnl** [comment]
Hello @shoucandanghehe 
neon has made another commit regarding this issue, can you test again?
should be fine to left the other downloaded segments and Collapse should only download the missing one
https://www.mediafire.com/file/4kaniqx53iu3e4v/Collapse-Debug_e51e5e40a3b23010cee91bac495e8c4b89f6fa34_net7.0-windows10.0.19041.0.7z/file
As always, let us know if you found a bug or issue with this build

**Comment by bagusnl** [comment]
Thank you for the confirmation! We will continue doing some checks and release the fix when we're ready
![image](https://github.com/neon-nyan/Collapse/assets/28079733/acd7d748-fff7-4df8-aaea-f1a62dcb0ff8)

**Comment by neon-nyan** [comment]
Hi @bagusnl, Thank you for backing me up.

Hi @shoucandanghehe,
We have already pushed the fixes for this and other issues in the latest v1.69.21 hotfix. Please update your launcher to the latest.
Thank you for reporting this and apologize for the inconvenience that occurred.
Also, we are going to close this issue in 24 hours and If you still have the same problem, feel free to let us know.
