### ISSUE TITLE
[GI][Repair] Persistance URI for Game Repair changed

### ISSUE THREAD

**Issue by bagusnl** [neon-nyan/Collapse#149]
This causes game repair wont download persistent caches.

Error log:
```
[Warn]  Failed parsing persistent manifest: release_res_versions_external (localName: release_res_versions_external_persist). Skipped!
Hi3Helper.Http.HttpHelperUnhandledError: HttpResponse for URL: "https://autopatchhk.yuanshen.com/client_game_res/3.7_live/output_14937036_558aa900c6/client/StandaloneWindows64/release_res_versions_external" has returned unsuccessful code: NotFound
   at Hi3Helper.Http.Http.InitializeSingleSession(Nullable`1 OffsetStart, Nullable`1 OffsetEnd, Boolean IsFileMode, Stream _Stream, Boolean IgnoreOutStreamLength)
   at Hi3Helper.Http.Http.<>c__DisplayClass63_0.<Download>b__0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at Hi3Helper.Http.Http.Download(String URL, String Output, Boolean Overwrite, Nullable`1 OffsetStart, Nullable`1 OffsetEnd, CancellationToken ThreadToken)
   at CollapseLauncher.GenshinRepair.ParseManifestToAssetIndex(Http _httpClient, String primaryParentURL, String secondaryParentURL, String manifestRemoteName, String manifestLocalName, String persistentPath, String streamingAssetsPath, List`1 assetIndex, Dictionary`2 hashtable, CancellationToken token)
  ```
  
  Causing code:
https://github.com/neon-nyan/Collapse/blob/e46fb12e8ed38ef31d2955e3b730209368b3023e/CollapseLauncher/Classes/RepairManagement/Genshin/Fetch.cs#L133-L137

New URI:
https://autopatchhk.yuanshen.com/client_game_res/3.7_live/output_14937036_558aa900c6/client/StandaloneWindows64/res_versions_external

**Comment by tilsgee** [comment]
Well, the bug still exist. just with different code but similar cause
System.UriFormatException: Invalid URI: The URI is empty.
   at System.Uri.CreateThis(String, Boolean, UriKind, UriCreationOptions& )
   at System.Uri..ctor(String uriString)
   at Hi3Helper.Http.Http.GetContentLengthAsync(String Input, CancellationToken token)
   at Hi3Helper.Http.Http.TryGetContentLengthAsync(String URL, CancellationToken Token)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.TryGetPackageRemoteSize(GameInstallPackage asset, CancellationToken token)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.GetPackagesRemoteSize(List`1 packageList, CancellationToken token)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.StartPackageDownload(Boolean skipDialog)
   at CollapseLauncher.Pages.HomePage.InstallGameDialog(Object sender, RoutedEventArgs e)

**Comment by bagusnl** [comment]
@tilsgee I believe that's for the game installation right?
If yes, the fix is already pushed to Stable branch, while there is another bug regarding that, currently it is possible to install Genshin with the new segmented zip scheme

This issue is specifically meant for GI Repair

**Comment by neon-nyan** [comment]
Hi @tilsgee,

I believe the issue is related to the Installation issue.
Please try updating your launcher to the latest stable release. Unfortunately, the fix didn't arrive to the preview release yet so you might need to switch to stable at the moment.
