### ISSUE TITLE
Honkai: The Star Rail Railway in China cannot be started, cannot be installed, and the startup error

### ISSUE THREAD

**Issue by mazhentao1992** [neon-nyan/Collapse#159]
System.FormatException: String '周三/23/4/05 上午 12:01:31' was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(ReadOnlySpan`1, DateTimeFormatInfo, DateTimeStyles)
   at System.DateTime.Parse(String, IFormatProvider )
   at System.Convert.ToDateTime(String, IFormatProvider)
   at System.String.System.IConvertible.ToDateTime(IFormatProvider)
   at System.Convert.ChangeType(Object, Type , IFormatProvider)
   at System.Convert.ChangeType(Object, Type )
   at SevenZipExtractor.ArchiveFile.GetProperty[T](UInt32 fileIndex, ItemPropId name) in E:\myGit\Collapse\Hi3Helper.Core\Classes\Data\Tools\SevenZipTool\SevenZipExtractor\SevenZipExtractor\ArchiveFile.cs:line 297
   at SevenZipExtractor.ArchiveFile.GetPropertySafe[T](UInt32 fileIndex, ItemPropId name) in E:\myGit\Collapse\Hi3Helper.Core\Classes\Data\Tools\SevenZipTool\SevenZipExtractor\SevenZipExtractor\ArchiveFile.cs:line 266
   at SevenZipExtractor.ArchiveFile.get_Entries() in E:\myGit\Collapse\Hi3Helper.Core\Classes\Data\Tools\SevenZipTool\SevenZipExtractor\SevenZipExtractor\ArchiveFile.cs:line 226
   at SevenZipExtractor.ArchiveFile..ctor(Stream archiveStream, Nullable`1 format, String libraryFilePath) in E:\myGit\Collapse\Hi3Helper.Core\Classes\Data\Tools\SevenZipTool\SevenZipExtractor\SevenZipExtractor\ArchiveFile.cs:line 103
   at Hi3Helper.Data.SevenZipTool.LoadArchive(String InputFile) in E:\myGit\Collapse\Hi3Helper.Core\Classes\Data\Tools\SevenZipTool.cs:line 30
   at Hi3Helper.Data.SevenZipTool.GetUncompressedSize(String inputFile) in E:\myGit\Collapse\Hi3Helper.Core\Classes\Data\Tools\SevenZipTool.cs:line 49
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.<>c__DisplayClass41_0.<StartPackageInstallation>b__1(GameInstallPackage x) in E:\myGit\Collapse\CollapseLauncher\Classes\InstallManagement\BaseClass\InstallManagerBase.cs:line 230
   at System.Linq.Enumerable.Sum[TSource,TResult,TAccumulator](IEnumerable`1, Func`2)
   at System.Linq.Enumerable.Sum[TSource](IEnumerable`1, Func`2)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.<StartPackageInstallation>b__41_0() in E:\myGit\Collapse\CollapseLauncher\Classes\InstallManagement\BaseClass\InstallManagerBase.cs:line 230
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__273_0(Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.StartPackageInstallation() in E:\myGit\Collapse\CollapseLauncher\Classes\InstallManagement\BaseClass\InstallManagerBase.cs:line 223
   at CollapseLauncher.Pages.HomePage.InstallGameDialog(Object sender, RoutedEventArgs e) in E:\myGit\Collapse\CollapseLauncher\XAMLs\MainApp\Pages\HomePage.xaml.cs:line 496

![image](https://github.com/neon-nyan/Collapse/assets/57353229/96ba16d2-701a-4259-b807-373bcc8f49e2)

**Comment by neon-nyan** [comment]
Hi @mazhentao1992,
We've pushed a new hotfix to fix this issue on the latest stable release, which is v1.69.21 version. Please make sure you've updated your launcher to the latest version.

We are going to close this issue in 24 hours and if you have any issues, feel free to let us know.
