### ISSUE TITLE
Can not make a quick or full fix in Honkai Star rail

### ISSUE THREAD

**Issue by Georgebillion** [neon-nyan/Collapse#162]
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String, Boolean, UriKind, UriCreationOptions& )
   at System.Uri..ctor(String uriString)
   at Hi3Helper.Http.Http.InitializeSingleSession(Nullable`1 OffsetStart, Nullable`1 OffsetEnd, Boolean IsFileMode, Stream _Stream, Boolean IgnoreOutStreamLength) in E:\myGit\Collapse\Hi3Helper.Http\Class\Session\SessionManager.cs:line 28
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at Hi3Helper.Http.Http.Download(String URL, Stream Outstream, Nullable`1 OffsetStart, Nullable`1 OffsetEnd, CancellationToken ThreadToken, Boolean IgnoreOutStreamLength) in E:\myGit\Collapse\Hi3Helper.Http\Http.cs:line 128
   at Hi3Helper.EncTool.Parser.AssetMetadata.SRDispatcherInfo.ParseArchive() in E:\myGit\Collapse\Hi3Helper.EncTool\Parser\SRMetadata\SRDispatcherInfo.cs:line 135
   at Hi3Helper.EncTool.Parser.AssetMetadata.SRDispatcherInfo.Initialize(CancellationToken threadToken, String persistentDirectory, String regionName) in E:\myGit\Collapse\Hi3Helper.EncTool\Parser\SRMetadata\SRDispatcherInfo.cs:line 81
   at Hi3Helper.EncTool.Parser.AssetMetadata.SRMetadata.Initialize(CancellationToken threadToken, String regionName, String persistentDirectory, Boolean forceInitialize) in E:\myGit\Collapse\Hi3Helper.EncTool\Parser\SRMetadata\SRMetadata.cs:line 66
   at CollapseLauncher.StarRailRepair.Fetch(List`1 assetIndex, CancellationToken token) in E:\myGit\Collapse\CollapseLauncher\Classes\RepairManagement\StarRail\Fetch.cs:line 34
   at CollapseLauncher.StarRailRepair.CheckRoutine() in E:\myGit\Collapse\CollapseLauncher\Classes\RepairManagement\StarRail\StarRailRepair.cs:line 57
   at CollapseLauncher.Interfaces.ProgressBase`2.TryRunExamineThrow(Task`1 action) in E:\myGit\Collapse\CollapseLauncher\Classes\Interfaces\Class\ProgressBase.cs:line 251
   at CollapseLauncher.StarRailRepair.StartCheckRoutine(Boolean useFastCheck) in E:\myGit\Collapse\CollapseLauncher\Classes\RepairManagement\StarRail\StarRailRepair.cs:line 33
   at CollapseLauncher.Pages.RepairPage.RunCheckRoutine(Object sender, Boolean isFast, Boolean isMainButton) in E:\myGit\Collapse\CollapseLauncher\XAMLs\MainApp\Pages\RepairPage.xaml.cs:line 59

**Comment by neon-nyan** [comment]
Hi @Georgebillion,

Thanks for the report.
We noticed that the gateway seems to be changed. We will investigate it further.

**Comment by Cryotechnic** [comment]
Fixed in [bf8153f](https://github.com/neon-nyan/Hi3Helper.EncTool/commit/bf8153f99491feabdcf3c71861adf887e45a3d3d). Will ship in v1.70.X if it has not already been shipped.

**Comment by Georgebillion** [comment]
but it still no function in 1.70.11

**Comment by Georgebillion** [comment]
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String, Boolean, UriKind, UriCreationOptions& )
   at System.Uri..ctor(String uriString)
   at Hi3Helper.Http.Http.InitializeSingleSession(Nullable`1 OffsetStart, Nullable`1 OffsetEnd, Boolean IsFileMode, Stream _Stream, Boolean IgnoreOutStreamLength)
   at Hi3Helper.Http.Http.<>c__DisplayClass66_0.<Download>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__273_0(Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at Hi3Helper.Http.Http.Download(String URL, Stream Outstream, Nullable`1 OffsetStart, Nullable`1 OffsetEnd, CancellationToken ThreadToken, Boolean IgnoreOutStreamLength)
   at Hi3Helper.EncTool.Parser.AssetMetadata.SRDispatcherInfo.ParseArchive()
   at Hi3Helper.EncTool.Parser.AssetMetadata.SRDispatcherInfo.Initialize(CancellationToken threadToken, String persistentDirectory, String regionName)
   at Hi3Helper.EncTool.Parser.AssetMetadata.SRMetadata.Initialize(CancellationToken threadToken, String regionName, String persistentDirectory, Boolean forceInitialize)
   at CollapseLauncher.StarRailRepair.Fetch(List`1 assetIndex, CancellationToken token)
   at CollapseLauncher.StarRailRepair.CheckRoutine()
   at CollapseLauncher.Interfaces.ProgressBase`2.TryRunExamineThrow(Task`1 action)
   at CollapseLauncher.StarRailRepair.StartCheckRoutine(Boolean useFastCheck)
   at CollapseLauncher.Pages.RepairPage.RunCheckRoutine(Object sender, Boolean isFast, Boolean isMainButton)
