### ISSUE TITLE
[Bug]: Can not make quick fix in Honkai Star Rail

### ISSUE THREAD

**Issue by Georgebillion** [neon-nyan/Collapse#182]
### Affected Version

Collaspe 1.70.11

### Bug Behavior

System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String, Boolean, UriKind, UriCreationOptions& )
   at System.Uri..ctor(String uriString)
   at Hi3Helper.Http.Http.InitializeSingleSession(Nullable`1 OffsetStart, Nullable`1 OffsetEnd, Boolean IsFileMode, Stream _Stream, Boolean IgnoreOutStreamLength)
   at Hi3Helper.Http.Http.<>c__DisplayClass66_0.<Download>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__273_0(Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at Hi3Helper.Http.Http.Download(String URL, Stream Outstream, Nullable`1 OffsetStart, Nullable`1 OffsetEnd, CancellationToken ThreadToken, Boolean IgnoreOutStreamLength)
   at Hi3Helper.EncTool.Parser.AssetMetadata.SRDispatcherInfo.ParseArchive()
   at Hi3Helper.EncTool.Parser.AssetMetadata.SRDispatcherInfo.Initialize(CancellationToken threadToken, String persistentDirectory, String regionName)
   at Hi3Helper.EncTool.Parser.AssetMetadata.SRMetadata.Initialize(CancellationToken threadToken, String regionName, String persistentDirectory, Boolean forceInitialize)
   at CollapseLauncher.StarRailRepair.Fetch(List`1 assetIndex, CancellationToken token)
   at CollapseLauncher.StarRailRepair.CheckRoutine()
   at CollapseLauncher.Interfaces.ProgressBase`2.TryRunExamineThrow(Task`1 action)
   at CollapseLauncher.StarRailRepair.StartCheckRoutine(Boolean useFastCheck)
   at CollapseLauncher.Pages.RepairPage.RunCheckRoutine(Object sender, Boolean isFast, Boolean isMainButton)

### Expected Behavior

fix it .

### Steps to reproduce

1.select to HSR-mainland China region
2.click game settings-fix game
3.click quick fix/full fix
4.Error!

### Related Issues

'#162' '#175'

### Additional Information

System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String, Boolean, UriKind, UriCreationOptions& )
   at System.Uri..ctor(String uriString)
   at Hi3Helper.Http.Http.InitializeSingleSession(Nullable`1 OffsetStart, Nullable`1 OffsetEnd, Boolean IsFileMode, Stream _Stream, Boolean IgnoreOutStreamLength)
   at Hi3Helper.Http.Http.<>c__DisplayClass66_0.<Download>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__273_0(Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at Hi3Helper.Http.Http.Download(String URL, Stream Outstream, Nullable`1 OffsetStart, Nullable`1 OffsetEnd, CancellationToken ThreadToken, Boolean IgnoreOutStreamLength)
   at Hi3Helper.EncTool.Parser.AssetMetadata.SRDispatcherInfo.ParseArchive()
   at Hi3Helper.EncTool.Parser.AssetMetadata.SRDispatcherInfo.Initialize(CancellationToken threadToken, String persistentDirectory, String regionName)
   at Hi3Helper.EncTool.Parser.AssetMetadata.SRMetadata.Initialize(CancellationToken threadToken, String regionName, String persistentDirectory, Boolean forceInitialize)
   at CollapseLauncher.StarRailRepair.Fetch(List`1 assetIndex, CancellationToken token)
   at CollapseLauncher.StarRailRepair.CheckRoutine()
   at Coll
apseLauncher.Interfaces.ProgressBase`2.TryRunExamineThrow(Task`1 action)
   at CollapseLauncher.StarRailRepair.StartCheckRoutine(Boolean useFastCheck)
   at CollapseLauncher.Pages.RepairPage.RunCheckRoutine(Object sender, Boolean isFast, Boolean isMainButton)

[log-2023-06-25-pre1.70.10-id1.log](https://github.com/neon-nyan/Collapse/files/11859923/log-2023-06-25-pre1.70.10-id1.log)
[log-2023-06-25-pre1.70.11-id0.log](https://github.com/neon-nyan/Collapse/files/11859924/log-2023-06-25-pre1.70.11-id0.log)
[DxDiag.txt](https://github.com/neon-nyan/Collapse/files/11859926/DxDiag.txt)

**Comment by neon-nyan** [comment]
Hi @Georgebillion
Have you tried changing the Repository CDN to Github or Bitbucket? Just making sure that your metadata is up-to-date.

Also, please try clearing the metadata by clicking the "Open App Data Folder" button in the App Settings menu -> delete "_metadata" folder -> Relaunch your launcher.

![image](https://github.com/neon-nyan/Collapse/assets/30566970/4948482e-5340-44f5-ab5b-0c751fa651a4)

> **Note: **Do the clearing after you changed the CDN to either Github or Bitbucket.

**Comment by bagusnl** [comment]
This one is closeable as discussed in Discord

**Comment by cocochick** [comment]
hello @neon-nyan , I meet the problem too. Here is some info.

**Affected Version**
Collaspe 1.70.12

**Log**

```
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String, Boolean, UriKind, UriCreationOptions& )
   at System.Uri..ctor(String uriString)
   at Hi3Helper.Http.Http.InitializeSingleSession(Nullable`1 OffsetStart, Nullable`1 OffsetEnd, Boolean IsFileMode, Stream _Stream, Boolean IgnoreOutStreamLength) in C:\Users\cryog\OneDrive\Documents\GitHub Repos\Collapse\Hi3Helper.Http\Class\Session\SessionManager.cs:line 28
   at Hi3Helper.Http.Http.<>c__DisplayClass66_0.<Download>b__0() in C:\Users\cryog\OneDrive\Documents\GitHub Repos\Collapse\Hi3Helper.Http\Http.cs:line 129
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__273_0(Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at Hi3Helper.Http.Http.Download(String URL, Stream Outstream, Nullable`1 OffsetStart, Nullable`1 OffsetEnd, CancellationToken ThreadToken, Boolean IgnoreOutStreamLength) in C:\Users\cryog\OneDrive\Documents\GitHub Repos\Collapse\Hi3Helper.Http\Http.cs:line 128
   at Hi3Helper.EncTool.Parser.AssetMetadata.SRDispatcherInfo.ParseArchive() in C:\Users\cryog\OneDrive\Documents\GitHub Repos\Collapse\Hi3Helper.EncTool\Parser\SRMetadata\SRDispatcherInfo.cs:line 162
   at Hi3Helper.EncTool.Parser.AssetMetadata.SRDispatcherInfo.Initialize(CancellationToken threadToken, String persistentDirectory, String regionName) in C:\Users\cryog\OneDrive\Documents\GitHub Repos\Collapse\Hi3Helper.EncTool\Parser\SRMetadata\SRDispatcherInfo.cs:line 81
   at Hi3Helper.EncTool.Parser.AssetMetadata.SRMetadata.Initialize(CancellationToken threadToken, String regionName, String persistentDirectory, Boolean forceInitialize) in C:\Users\cryog\OneDrive\Documents\GitHub Repos\Collapse\Hi3Helper.EncTool\Parser\SRMetadata\SRMetadata.cs:line 66
   at CollapseLauncher.StarRailRepair.Fetch(List`1 assetIndex, CancellationToken token) in C:\Users\cryog\OneDrive\Documents\GitHub Repos\Collapse\CollapseLauncher\Classes\RepairManagement\StarRail\Fetch.cs:line 33
   at CollapseLauncher.StarRailRepair.CheckRoutine() in C:\Users\cryog\OneDrive\Documents\GitHub Repos\Collapse\CollapseLauncher\Classes\RepairManagement\StarRail\StarRailRepair.cs:line 57
   at CollapseLauncher.Interfaces.ProgressBase`2.TryRunExamineThrow(Task`1 action) in C:\Users\cryog\OneDrive\Documents\GitHub Repos\Collapse\CollapseLauncher\Classes\Interfaces\Class\ProgressBase.cs:line 251
   at CollapseLauncher.StarRailRepair.StartCheckRoutine(Boolean useFastCheck) in C:\Users\cryog\OneDrive\Documents\GitHub Repos\Collapse\CollapseLauncher\Classes\RepairManagement\StarRail\StarRailRepair.cs:line 33
   at CollapseLauncher.Pages.RepairPage.RunCheckRoutine(Object sender, Boolean isFast, Boolean isMainButton) in C:\Users\cryog\OneDrive\Documents\GitHub Repos\Collapse\CollapseLauncher\XAMLs\MainApp\Pages\RepairPage.xaml.cs:line 59
```
I have already changed the Repository CDN to Github, and delete "_metadata" folder , but it doesn't work.

**Comment by bagusnl** [comment]
Hi @cocochick !
We are aware for the issue and due to the latest update of HSR, both Glb and CN game repair and cache update are broken. We are still investigating the issue and will provide a fix once its ready!
