### ISSUE TITLE
[Bug]: Exception while downloading game

### ISSUE THREAD

**Issue by LADIlib** [neon-nyan/Collapse#210]
### Affected Version

Collapse 1.70.12

### Bug Behavior

Go into game settings in side menu while package is downloading.

```
System.IO.IOException: The process cannot access the file 'C:\Games\SRGlb\Games\StarRail_1.2.0.zip.277680' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.FileStream..ctor(String, FileMode, FileAccess, FileShare, Int32, Boolean)
   at System.IO.FileStream..ctor(String, FileMode, FileAccess)
   at Hi3Helper.Http.Session..ctor(String PathURL, String PathOutput, Stream SOutput, CancellationToken SToken, Boolean IsFileMode, HttpClientHandler ClientHandler, Nullable`1 OffsetStart, Nullable`1 OffsetEnd, Boolean Overwrite, String UserAgent, Boolean UseExternalSessionClient, Boolean IgnoreOutStreamLength) in C:\Users\cryog\OneDrive\Documents\GitHub Repos\Collapse\Hi3Helper.Http\Class\Session\Session.cs:line 42
   at Hi3Helper.Http.Http.InitializeMultiSession() in C:\Users\cryog\OneDrive\Documents\GitHub Repos\Collapse\Hi3Helper.Http\Class\Session\SessionManager.cs:line 151
   at Hi3Helper.Http.Http.Download(String URL, String Output, Byte ConnectionSessions, Boolean Overwrite, CancellationToken ThreadToken) in C:\Users\cryog\OneDrive\Documents\GitHub Repos\Collapse\Hi3Helper.Http\HttpMulti.cs:line 46
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.RunPackageDownloadRoutine(GameInstallPackage package, CancellationToken token, Int32 packageCount) in C:\Users\cryog\OneDrive\Documents\GitHub Repos\Collapse\CollapseLauncher\Classes\InstallManagement\BaseClass\InstallManagerBase.cs:line 974
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.InvokePackageDownloadRoutine(List`1 packageList, CancellationToken token) in C:\Users\cryog\OneDrive\Documents\GitHub Repos\Collapse\CollapseLauncher\Classes\InstallManagement\BaseClass\InstallManagerBase.cs:line 951
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.StartPackageDownload(Boolean skipDialog) in C:\Users\cryog\OneDrive\Documents\GitHub Repos\Collapse\CollapseLauncher\Classes\InstallManagement\BaseClass\InstallManagerBase.cs:line 151
   at CollapseLauncher.Pages.HomePage.InstallGameDialog(Object sender, RoutedEventArgs e) in C:\Users\cryog\OneDrive\Documents\GitHub Repos\Collapse\CollapseLauncher\XAMLs\MainApp\Pages\HomePage.xaml.cs:line 719
```

### Expected Behavior

No exception

### Steps to reproduce

1. Start downloading package
![image](https://github.com/neon-nyan/Collapse/assets/39984678/ae81a071-89f6-4adb-a641-8e74641341ee)
2. Go into game settings (is side menu) before downloading done
![image](https://github.com/neon-nyan/Collapse/assets/39984678/67b7b790-0cb4-49a3-94a9-a91c339c85cb)
![image](https://github.com/neon-nyan/Collapse/assets/39984678/7c02ac36-af39-4eda-96cf-8b96bde1e451)
4. Go back to Launcher window
5. Start downloading again (?)
6. See exception

### Screenshot(s)

![image](https://github.com/neon-nyan/Collapse/assets/39984678/65ca0d1b-650c-4423-aca7-8515c3a37749)

**Comment by bagusnl** [comment]
Hi, sorry for quite a late update!
We already submitted a fix in the code that will invoke `PageStatics._GameInstall.CancelRoutine();` when MainPage is unloaded, so that game installation download will cancel and release the file so it can be started again after going back to the main page.
This fix is in #213 that we are planning to merge and release a preview soon(tm)

Thank you for submitting the bug report!

**Comment by bagusnl** [comment]
As we have merged the new implementation for download, its only waiting for the stable to get it. We will close the issue once stable is synced to 1.71.x

**Comment by bagusnl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Background Download by @neon-nyan](https://trello.com/c/2lf94ubn/9-background-download-by-neon-nyan)
