### ISSUE TITLE
[bug]Network issues in the China region

### ISSUE THREAD

**Issue by misaka10843** [neon-nyan/Collapse#64]
In mainland China, for some reason, the government blocks users from accessing GitHub in the normal way from time to time, which can cause some features of the launcher to fail (such as updates)

```
获取版本发行说明时出错. System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream. at System.Net.Security.SslStream.ReceiveBlobAsyncTIOAdapter at System.Net.Security.SslStream.ForceAuthenticationAsyncTIOAdapter at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem) at System.Threading.Tasks.TaskCompletionSourceWithCancellation1.WaitWithCancellationAsync(Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter1 OffsetStart, Nullable1 OffsetStart, Nullable`1 OffsetEnd, CancellationToken ThreadToken) in C:\myGit\CollapseLauncher\Hi3Helper.Http\Http.cs:line 119 at CollapseLauncher.Pages.UpdatePage.GetReleaseNote() in C:\myGit\CollapseLauncher\CollapseLauncher\XAMLs\MainApp\Pages\UpdatePage.xaml.cs:line 55
```

Although this is a minor issue, if possible, I would like to be able to use mirror sites when GitHub.com and related domains are detected as inaccessible, for example, to access the `icon.ico` in `CollapseLauncher` you can use `https://cdn.staticaly.com/gh/neon-nyan/ Collapse/main/CollapseLauncher/icon.ico`
Or add a proxy option to the settings page

But in general, the problem can be fixed without any particular urgency because we have adapted to it, or without fixing it if it is difficult (but access is faster after the fix)

![](https://upload-bbs.miyoushe.com/upload/2022/12/08/a2fa805a0a782cdb8ab44ddaf8d5343d_7408497524870727211.png)

**Comment by neon-nyan** [comment]
I see, thank you for letting me know about this!
I'm going to keeping this in-mind and implement this to be used as a mirror in the future.

**Comment by Cryotechnic** [comment]
@neon-nyan Pinging you since the only sensible way to change this would be to add a `fallbackurl` for the `Updater` calls in the project. I'm currently implementing some changes on my [branch](https://github.com/Cryotechnic/CollapseLauncher/tree/fallback-ssl) but unsure how to test them. Let me know what you think, this isn't really a priority but should be an easy fix because there are only 4 calls for `Updater` in the project. Commit 6f1383ea99c0d6d3bc5dfa963a3614fc0c0cdd57 on my repo adds the bool flag.

Another way to solve this would be to just take a CDN available globally (like Staticaly, Cloudflare, etc.) and change the URLs to that. For now I've just implemented a `bool` flag to toggle between `RepoURL` & `FallbackRepoURL`.

**Comment by neon-nyan** [comment]
@Cryotechnic I'll be trying your commit and hope I could give you a feedback about it tonight.

**Comment by neon-nyan** [comment]
I'm very sorry for my very late update on this.
I've just checked the code and I think we can make a PR for this as the first phase of the implementation.

**Comment by Cryotechnic** [comment]
Sounds good, I'll open the PR after re-verifying the code on my end and we can keep iterating on it should the need arise.

**Comment by Cryotechnic** [comment]
This feature has now been implemented and should hopefully be released to the public in the next major version. Thanks for the idea!

**Comment by misaka10843** [comment]
Hi, thank you very much for adding the CDN server, but I found out, can you select the CDN server before loading the game list?
Because if you don't you're still going to get an error and keep showing loads

![image](https://user-images.githubusercontent.com/69132853/220527815-dc34c987-e2bf-47a8-8df6-cee5669575d7.png)


```log
[Schm] [13:04:05.545]  You're running v1.0.69.1 Preview under Windows 11 (build: 22623.0) as misaka10843
[Schm] [13:04:05.856]  Locale file: en.json loaded as English by neon-nyan, CryoTechnic
[Schm] [13:04:05.862]  Locale file: id-ID.json loaded as Bahasa Indonesia by neon-nyan
[Schm] [13:04:05.868]  Locale file: pt-pt.json loaded as Português (Portugal) by gablm
[Schm] [13:04:05.874]  Locale file: zh-cn.json loaded as 简体中文 by misaka10843
s.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Hi3Helper.Http.Http.InitializeSingleSession(Nullable`1 OffsetStart, Nullable`1 OffsetEnd, Boolean IsFileMode, Stream _Stream, Boolean IgnoreOutStreamLength) in C:\myGit\CollapseLauncher\Hi3Helper.Http\Class\Session\SessionManager.cs:line 41
   at Hi3Helper.Http.Http.<>c__DisplayClass56_0.<Download>b__0() in C:\myGit\CollapseLauncher\Hi3Helper.Http\Http.cs:line 131
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Hi3Helper.Http.Http.Download(String URL, Stream Outstream, Nullable`1 OffsetStart, Nullable`1 OffsetEnd, CancellationToken ThreadToken, Boolean IgnoreOutStreamLength) in C:\myGit\CollapseLauncher\Hi3Helper.Http\Http.cs:line 130
   at CollapseLauncher.LauncherUpdateWatcher.StartCheckUpdate() in C:\myGit\CollapseLauncher\CollapseLauncher\Classes\EventsManagement\EventsHandler.cs:line 49

```

**Comment by neon-nyan** [comment]
Hi @misaka10843,

A good news for you.
The implementation of the CDN selector has been completed and it will be coming in the next preview release and also in the next stable release thanks to the initial implementation for hit (PR: #71 by @Cryotechnic) and also in this recent commit: https://github.com/neon-nyan/Collapse/commit/719c21e2f810d0acf1a8cad23e2a147f94337a16

![](https://cdn.discordapp.com/emojis/895275262567129130.png)

**Comment by misaka10843** [comment]
> Hi @misaka10843,
> 
> A good news for you. The implementation of the CDN selector has been completed and it will be coming in the next preview release and also in the next stable release thanks to the initial implementation in this PR: #71 by @Cryotechnic and also in this recent commit: [719c21e](https://github.com/neon-nyan/Collapse/commit/719c21e2f810d0acf1a8cad23e2a147f94337a16)
> 
> ![](https://camo.githubusercontent.com/0b80c9b68840f783d37f95a086a9e5a880aed9a87aef72d8a2a75a3989da0d93/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3839353237353236323536373132393133302e706e67)

Ok, thank you and Cryotechnic so much!
