### ISSUE TITLE
Cant continoue download

### ISSUE THREAD

**Issue by HizrianPratama** [neon-nyan/Collapse#80]
System.NullReferenceException: Oops, the launcher cannot finalize the installation but don't worry, your game has been totally updated.
	Please report this issue to our GitHub here: https://github.com/neon-nyan/CollapseLauncher/issues/new or come back to the launcher and make sure to use Repair Game in Game Settings button later.
Throw: System.NullReferenceException: Object reference not set to an instance of an object.
   at Hi3Helper.Http.Http.InitializeMultiSession() in C:\myGit\Collapse-Legacy\Hi3Helper.Http\Class\Session\SessionManager.cs:line 188
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Hi3Helper.Http.Http.Download(String URL, String Output, Byte ConnectionSessions, Boolean Overwrite, CancellationToken ThreadToken) in C:\myGit\Collapse-Legacy\Hi3Helper.Http\HttpMulti.cs:line 47
   at CollapseLauncher.InstallManagement.StartDownloadAsync() in C:\myGit\Collapse-Legacy\CollapseLauncher\Classes\InstallManagement\InstallManagement.cs:line 195
   at CollapseLauncher.Pages.HomePage.UpdateGameDialog(Object sender, RoutedEventArgs e) in C:\myGit\Collapse-Legacy\CollapseLauncher\XAMLs\MainApp\Pages\HomePage.xaml.cs:line 1406
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Hi3Helper.Http.Http.InitializeMultiSession() in C:\myGit\Collapse-Legacy\Hi3Helper.Http\Class\Session\SessionManager.cs:line 188
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Hi3Helper.Http.Http.Download(String URL, String Output, Byte ConnectionSessions, Boolean Overwrite, CancellationToken ThreadToken) in C:\myGit\Collapse-Legacy\Hi3Helper.Http\HttpMulti.cs:line 47
   at CollapseLauncher.InstallManagement.StartDownloadAsync() in C:\myGit\Collapse-Legacy\CollapseLauncher\Classes\InstallManagement\InstallManagement.cs:line 195
   at CollapseLauncher.Pages.HomePage.UpdateGameDialog(Object sender, RoutedEventArgs e) in C:\myGit\Collapse-Legacy\CollapseLauncher\XAMLs\MainApp\Pages\HomePage.xaml.cs:line 1406
   --- End of inner exception stack trace ---

**Comment by neon-nyan** [comment]
Could you please tell us what version do you use?

**Comment by neon-nyan** [comment]
Closing this issue for now as the fix will be shipped in the next stable release
