### ISSUE TITLE
Pre-updates Failing for Genshin/Honkai past few versions.

### ISSUE THREAD

**Issue by KawaiiSoCKs** [neon-nyan/Collapse#98]
Recent Honkai log provided below, I usually have to completely restart the update or use an Hoyo official launcher to get it to properly install.

> System.NullReferenceException: Oops, the launcher cannot finalize the installation but don't worry, your game has been totally updated.
	Please report this issue to our GitHub here: https://github.com/neon-nyan/CollapseLauncher/issues/new or come back to the launcher and make sure to use Repair Game in Game Settings button later.
Throw: System.NullReferenceException: Object reference not set to an instance of an object.
   at Hi3Helper.Http.Http.InitializeMultiSession() in C:\myGit\Collapse-Legacy\Hi3Helper.Http\Class\Session\SessionManager.cs:line 188
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Hi3Helper.Http.Http.Download(String URL, String Output, Byte ConnectionSessions, Boolean Overwrite, CancellationToken ThreadToken) in C:\myGit\Collapse-Legacy\Hi3Helper.Http\HttpMulti.cs:line 47
   at CollapseLauncher.InstallManagement.StartDownloadAsync() in C:\myGit\Collapse-Legacy\CollapseLauncher\Classes\InstallManagement\InstallManagement.cs:line 195
   at CollapseLauncher.Pages.HomePage.UpdateGameDialog(Object sender, RoutedEventArgs e) in C:\myGit\Collapse-Legacy\CollapseLauncher\XAMLs\MainApp\Pages\HomePage.xaml.cs:line 1406
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Hi3Helper.Http.Http.InitializeMultiSession() in C:\myGit\Collapse-Legacy\Hi3Helper.Http\Class\Session\SessionManager.cs:line 188
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Hi3Helper.Http.Http.Download(String URL, String Output, Byte ConnectionSessions, Boolean Overwrite, CancellationToken ThreadToken) in C:\myGit\Collapse-Legacy\Hi3Helper.Http\HttpMulti.cs:line 47
   at CollapseLauncher.InstallManagement.StartDownloadAsync() in C:\myGit\Collapse-Legacy\CollapseLauncher\Classes\InstallManagement\InstallManagement.cs:line 195
   at CollapseLauncher.Pages.HomePage.UpdateGameDialog(Object sender, RoutedEventArgs e) in C:\myGit\Collapse-Legacy\CollapseLauncher\XAMLs\MainApp\Pages\HomePage.xaml.cs:line 1406
   --- End of inner exception stack trace ---

**Comment by bagusnl** [comment]
Apologizes for late update but we are aware of the issue and neon is currently working on a fix. 

Tracking issue over at #96

**Comment by Cryotechnic** [comment]
Referencing issue #96, this is now being closed as 1.69.7 fixes this issue!

Thank you for the report!
